### PR TITLE
Migrated to bevy 0.13 and rapier 0.25

### PR DESCRIPTION
**Pull request by SirRoderickYammins**
Followed migration guide. Changed ```Input``` -> ```ButtonInput``` and KeyCodes start with "Key" now instead of just the letter name.

### CODE REVIEW

**Comment by qhdwight** [comment]
Sorry, was in the middle of midterms, taking a look now

Thank you for updating

**Comment by qhdwight** [comment]
Normally I would prefer people not committing formatting changes too but this one seems somewhat reasonable so it is fine.

**Comment by qhdwight** [comment]
Hmm at least on my computer the shadows are really dark in the example world. I'll scan the update notes to see if we are missing something

**Review by qhdwight — APPROVED** [review]

**Comment by SirRoderickYammins** [comment]
Thanks! I did notice the shadows were also darker on my end, but wasn't sure if it was just me.

Was my first pull request, thanks!

**Pull request merged**
