### PR TITLE
implement always_run

### PR DESCRIPTION
**Pull request by BrianWiz**
A simple addition that allows running by default. Left shift then becomes walk.

### CODE REVIEW

**Comment by qhdwight** [comment]
I think I would prefer if end users wrote a custom input system that filled out `FpsControllerInput` to their needs.

I can see the number of desired input configurations skyrocketing and I want to keep it simple.

**Comment by BrianWiz** [comment]
Makes sense! btw @qhdwight how interested are you in a MP version of this controller? Something I'm working on, using Renet.

**Comment by qhdwight** [comment]
Definitely interested! Haven't played around with networking too much in Bevy though.

**Comment by qhdwight** [comment]
> Makes sense! btw @qhdwight how interested are you in a MP version of this controller? Something I'm working on, using Renet.

Feel free to open up a discussion: https://github.com/qhdwight/bevy_fps_controller/discussions

**Pull request closed without merging**
