### PR TITLE
fix: Removes wall climbing

### PR DESCRIPTION
**Pull request by rafaeldelboni**
Closes: https://github.com/qhdwight/bevy_fps_controller/issues/2

### CODE REVIEW

**Comment by qhdwight** [comment]
Will test it right now, I also see you bumped the versions, thank you for that

**Comment by rafaeldelboni** [comment]
I forgot to bump the crate version, do you want me to do that?

**Comment by qhdwight** [comment]
> I forgot to bump the crate version, do you want me to do that?

Yes please!

**Comment by qhdwight** [comment]
I also tested it - works great. Thank you for making the PR.

**Review by qhdwight — APPROVED** [review]

**Pull request merged**
